alter table aplica add constraint fk_aplicaDEPO foreign key (idDeporte) references deportes(idDeporte);
alter table aplica add constraint fk_aplicaRESU foreign key (idResultado) references resultados(idResultado);
alter table competencia_colectiva add constraint fk_compCole foreign key (idEncuentro) references encuentros(idEncuentro);
alter table competencia_individual add constraint fk_compIndi foreign key (idEncuentro) references encuentros(idEncuentro);
alter table compite add constraint fk_compiteENCU foreign key (idEncuentro) references encuentros(idEncuentro);
alter table compite add constraint fk_compiteEQUI foreign key (idEquipo) references equipos(idEquipo);
alter table compite add constraint fk_compiteJUGA foreign key (idJugador) references jugador(idJugador);
alter table deportesfavoritos add constraint fk_depoFavUSU foreign key (idUsuario) references usuarios(idUsuario);
alter table deportesfavoritos add constraint fk_depoFavDEPO foreign key (deporteFavorito) references deportes(idDeporte);
alter table fase add constraint fk_fase foreign key (idTorneo) references torneos(idTorneo);
alter table forman add constraint fk_formanJUGA foreign key (idJugador) references jugador(idJugador);
alter table forman add constraint fk_formanEQUI foreign key (idEquipo) references equipos(idEquipo);
alter table guest add constraint fk_guest foreign key (idUsuario) references usuarios(idUsuario);
alter table instrucciones add constraint fk_instru foreign key (idReglas) references reglas(idReglas);
alter table participa add constraint fk_partiENCUE foreign key (idEncuentro) references encuentros(idEncuentro);
alter table participa add constraint fk_partiPARTI foreign key (idParticipante) references participantes(idParticipante);
alter table poseen add constraint fk_poseenDEPO foreign key (idDeporte) references deportes(idDeporte);
alter table poseen add constraint fk_poseenREG foreign key (idReglas) references reglas(idReglas);
alter table practican add constraint fk_pracJUGA foreign key (idJugador) references jugador(idJugador);
alter table practican add constraint fk_pracEQUI foreign key (idEquipo) references equipos(idEquipo);
alter table practican add constraint fk_pracDEPO foreign key (idDeporte) references deportes(idDeporte);
alter table practican add constraint fk_pracRESU foreign key (idResultado) references resultados(idResultado);
alter table rankings add constraint fk_rankings foreign key (idResultado) references resultados(idResultado);
alter table rounds add constraint fk_rounds foreign key (idDuracion) references duracion(idDuracion);
alter table sanciones add constraint fk_sancion foreign key (idReglas) references reglas(idReglas);
alter table se_especializa_en add constraint fk_seEspeDEPO foreign key (idDeporte) references deportes(idDeporte);
alter table se_especializa_en add constraint fk_seEspeRESU foreign key (idResultado) references resultados(idResultado);
alter table se_especializa_en add constraint fk_seEspePARTI foreign key (idParticipante) references participantes(idParticipante);
alter table sets add constraint fk_sets foreign key (idDuracion) references duracion(idDuracion);
alter table tiempo add constraint fk_tiempo foreign key (idDuracion) references duracion(idDuracion);
alter table tiene add constraint fk_tieneFASE foreign key (idTorneo,nFases) references fase(idTorneo,nFases);
alter table tiene add constraint fk_tieneENCU foreign key (idEncuentro) references encuentros(idEncuentro);
alter table tiene_usuario add constraint fk_tiene_usuPUB foreign key (idPublicidad) references publicidad(idPublicidad);
alter table tiene_usuario add constraint fk_tiene_usuUSU foreign key (idUsuario) references guest(idUsuario);
alter table vip add constraint fk_vip foreign key (idUsuario) references usuarios(idUsuario);
alter table visualiza add constraint fk_visaUSU foreign key (idUsuario) references usuarios(idUsuario);
alter table visualiza add constraint fk_visaENCU foreign key (idEncuentro) references encuentros(idEncuentro);
alter table deportes add constraint ck_depoCantJuga check (cantidadJugadores > 1);
alter table encuentros add constraint ck_encuDia check (dia < 32);
alter table encuentros add constraint ck_encuDia2 check (dia > 0);
alter table encuentros add constraint dk_encuMes check (mes < 13);
alter table encuentros add constraint dk_encuMes2 check (mes > 0);
alter table encuentros add constraint ck_encuAnio check (anio > 2000);
alter table encuentros add constraint ck_encuHora check (hora < 24);
alter table encuentros add constraint ck_encuHora2 check (hora >= 0);
alter table encuentros add constraint ck_encuMinuto check (minuto < 61);
alter table encuentros add constraint ck_encuMinuto2 check (minuto >=0);
alter table encuentros alter column termino set default 0;
alter table jugador add constraint ck_jugaEdad check(edad > 17);
alter table jugador add constraint ck_jugaSexo check(sexo = 'f' or sexo = 'm');
alter table participantes add constraint ck_partiEdad check(edad > 5);
alter table participantes add constraint ck_partiSexo check(sexo = 'f' or sexo = 'm');
alter table tiempo add constraint ck_tiempoHoras check(horas >= 0);
alter table tiempo add constraint ck_tiempoHoras2 check(horas < 25);
alter table tiempo add constraint ck_tiempoMinu check(minutos < 61);
alter table tiempo add constraint ck_tiempoMinu2 check(minutos >= 0);
alter table usuarios add constraint ck_usuRol check(rol <= 0);
alter table vip add constraint ck_vipMesesSus check(mesesSuscritos > 0);




